---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "defaults.yml"

- name: Set facts
  set_fact:
    telepresence_packages: "{{ __telepresence_packages | list }}"

- name: Ensure system certificates are installed
  package:
    name: "{{ telepresence_packages }}"
    state: present
  become: yes

- name: Download telepresence binary to {{ telepresence_bin_path }}
  get_url:
    url: "https://app.getambassador.io/download/tel2/linux/{{ telepresence_arch }}/{{ telepresence_version }}/telepresence"
    dest: "{{ telepresence_bin_path }}/telepresence"
    owner: "{{ telepresence_user }}"
    group: "{{ telepresence_group }}"
    mode: 0755
  become: yes
