---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Install latest ca-certificates on CentOS 7 or lower
      ansible.builtin.yum:
        name:
          - ca-certificates
        state: present
        update_cache: true
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version <= "7")

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
