---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    telepresence_bin_path: "/usr/local/bin"
    telepresence_version: "v2.14.4"
  tasks:
    - name: Ensure Telepresence is installed.
      ansible.builtin.stat:
        path: "{{ telepresence_bin_path }}/telepresence"
      register: this_stat

    - name: Get version from Telepresence.
      ansible.builtin.command: "{{ telepresence_bin_path }}/telepresence version"
      register: this_exec

    - name: Assert binary exists
      ansible.builtin.assert:
        that:
          - this_stat.stat.exists

    - name: Assert version is correct
      ansible.builtin.assert:
        that:
          - telepresence_version in this_exec.stdout
