---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    telepresence_bin_path: "/usr/local/bin"
    telepresence_version: "Client: v2.4.9 (api v3)"
  tasks:
    - name: Ensure Telepresence is installed.
      stat:
        path: "{{ telepresence_bin_path }}/telepresence"
      register: this_stat

    - name: Get version from Telepresence.
      command: "{{ telepresence_bin_path }}/telepresence version"
      register: this_exec

    - assert:
        that:
          - this_stat.stat.exists

    - assert:
        that:
          - this_exec.stdout_lines[0] == telepresence_version
